# Generated by Django 2.2.1 on 2019-06-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RushNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('eventtype', models.CharField(choices=[('IN', 'Interview Night'), ('SO', 'Social Night'), ('GA', 'Game Night'), ('SP', 'Speaker Night'), ('VO', 'Voting Night'), ('OT', 'Other')], default='SO', max_length=2)),
                ('comment', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('address', models.CharField(max_length=200, verbose_name='School Address')),
                ('cellphone', models.CharField(max_length=30, verbose_name='Cell Phone Number')),
                ('gpa', models.IntegerField(choices=[(1, 'This is my first semester.'), (2, 'Less Than 2.0'), (3, 'Between 2.0 and 2.5'), (4, 'Between 2.5 and 2.75'), (5, 'Between 2.75 and 3.0'), (6, 'Between 3.0 and 3.25'), (7, 'Between 3.25 and 3.5'), (8, 'Between 3.5 and 3.75'), (9, 'Above 3.75')], default=1, verbose_name='College GPA*')),
                ('involvement', models.CharField(blank=True, max_length=300, null=True, verbose_name='What are you involved with on campus?*')),
                ('WhyAKPsi', models.CharField(max_length=500, null=True, verbose_name='Why do you want to be part of AKPsi?*')),
                ('HowDidYouHear', models.CharField(blank=True, max_length=200, null=True, verbose_name='How did you hear about AKPsi?')),
                ('excuses', models.CharField(blank=True, max_length=200, null=True, verbose_name='Do you have any conflicts with any nights of rush? If so what are they? If not leave blank*')),
                ('aboutme', models.CharField(blank=True, max_length=400, null=True, verbose_name="Please use the space below to write an 'About Me'*")),
                ('essaytopic', models.IntegerField(blank=True, choices=[(1, 'What is something you are passionate about?'), (2, 'Talk about a time you failed and how you responded.'), (3, 'When is a time you had to be a leader?'), (4, 'Talk about a time you had to go above and beyond?'), (5, 'What specific ways can you contribute to Alpha Kappa Psi?')], null=True, verbose_name='Choose an Essay Topic Below!')),
                ('essay', models.CharField(blank=True, max_length=3500, null=True, verbose_name='Use The Space Below to Write a Short (less than 500 words) Essay About Your Selected Topic!*')),
                ('rushee', models.ForeignKey(limit_choices_to={'profile.isbrother': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Abstain')], default=3)),
                ('brother', models.ForeignKey(limit_choices_to={'profile.isbrother': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rushee', models.ForeignKey(limit_choices_to={'profile.isbrother': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('brother', 'rushee')},
            },
        ),
        migrations.CreateModel(
            name='RusheeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.RushNight')),
                ('rushee', models.ForeignKey(limit_choices_to={'profile.isbrother': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rushee', 'night')},
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentiontype', models.IntegerField(choices=[(1, 'Positive'), (2, 'Negative')], default=1, verbose_name='Type of Mention')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='Comment')),
                ('brother', models.ForeignKey(limit_choices_to={'profile.isbrother': True}, on_delete=django.db.models.deletion.CASCADE, related_name='mentiongiven', to=settings.AUTH_USER_MODEL)),
                ('night', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.RushNight')),
                ('rushee', models.ForeignKey(limit_choices_to={'profile.isbrother': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('night', 'rushee', 'brother'),
                'unique_together': {('brother', 'rushee')},
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField(choices=[(3, '3'), (1, '1'), (2, '2'), (4, '4'), (5, '5')])),
                ('energy', models.IntegerField(choices=[(3, '3'), (1, '1'), (2, '2'), (4, '4'), (5, '5')])),
                ('friendliness', models.IntegerField(choices=[(3, '3'), (1, '1'), (2, '2'), (4, '4'), (5, '5')])),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Negative Comments Only')),
                ('interviewer', models.ForeignKey(limit_choices_to={'profile.isbrother': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rushee', models.ForeignKey(limit_choices_to={'profile.isbrother': False}, on_delete=django.db.models.deletion.CASCADE, related_name='interviewgiven', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('interviewer', 'rushee')},
            },
        ),
    ]
