# Generated by Django 2.2.1 on 2019-06-25 22:21

from django.db import migrations, models
import rush.models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rushnight',
            name='eventtype',
        ),
        migrations.AddField(
            model_name='rushnight',
            name='enableinterviews',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='rushnight',
            name='enablevoting',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='rushnight',
            name='night',
            field=models.IntegerField(default=1, unique=True, validators=[rush.models.validate_not_negative]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='energy',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (3, '3'), (5, '5'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='friendliness',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (3, '3'), (5, '5'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interest',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (3, '3'), (5, '5'), (1, '1')]),
        ),
    ]
