# Generated by Django 2.2.1 on 2019-06-26 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rush', '0002_auto_20190625_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RusheeAttendance',
            new_name='RusheeSignin',
        ),
        migrations.AlterField(
            model_name='interview',
            name='energy',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (3, '3'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='friendliness',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (3, '3'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interest',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (3, '3'), (1, '1')]),
        ),
    ]
