# Generated by Django 2.2.1 on 2019-06-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0003_auto_20190625_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rushnight',
            old_name='enableinterviews',
            new_name='interviews',
        ),
        migrations.RenameField(
            model_name='rushnight',
            old_name='enablevoting',
            new_name='voting',
        ),
        migrations.AlterField(
            model_name='interview',
            name='energy',
            field=models.IntegerField(choices=[(4, '4'), (3, '3'), (5, '5'), (2, '2'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='friendliness',
            field=models.IntegerField(choices=[(4, '4'), (3, '3'), (5, '5'), (2, '2'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interest',
            field=models.IntegerField(choices=[(4, '4'), (3, '3'), (5, '5'), (2, '2'), (1, '1')]),
        ),
    ]
