# Generated by Django 2.2.1 on 2019-07-02 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0005_auto_20190701_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(max_length=200, verbose_name='School Address (Used for bid delivery)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cellphone',
            field=models.CharField(max_length=30, verbose_name='Cell Phone Number (Used for bid delivery)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='essay',
            field=models.CharField(blank=True, max_length=3500, verbose_name='Write a Short (less than 500 words) Essay About Your Selected Topic!*'),
        ),
        migrations.AlterField(
            model_name='application',
            name='essaytopic',
            field=models.IntegerField(blank=True, choices=[(1, 'What is something you are passionate about?'), (2, 'Talk about a time you failed and how you responded.'), (3, 'When is a time you had to be a leader?'), (4, 'Talk about a time you had to go above and beyond?'), (5, 'What specific ways can you contribute to Alpha Kappa Psi?')], verbose_name='Essay Topic*'),
        ),
        migrations.AlterField(
            model_name='application',
            name='excuses',
            field=models.CharField(blank=True, max_length=200, verbose_name='Any conflicts with any nights of rush? If so, what are they? If not, leave blank*'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rushee',
            field=models.OneToOneField(limit_choices_to={'profile__isbrother': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2, verbose_name='Year*'),
        ),
    ]
