# Generated by Django 2.2.1 on 2019-07-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0006_auto_20190701_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('A', 'Abstain'), ('N', 'No'), ('Y', 'Yes')], default='A', max_length=1),
        ),
    ]
