# Generated by Django 2.2.1 on 2019-07-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0007_auto_20190702_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='mentiontype',
            field=models.CharField(choices=[('P', 'Positive'), ('N', 'Negative')], default='P', max_length=1, verbose_name='Type of Mention'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('A', 'Abstain')], default='A', max_length=1),
        ),
    ]
