# Generated by Django 2.2.1 on 2019-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190621_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isbrother',
            field=models.BooleanField(default=False),
        ),
    ]
