version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./src:/src
      - ./static:/static
      - ./media:/media
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - akpsi
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - akpsi
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  akpsi:
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn akpsi.wsgi -b 0.0.0.0:8000"
    container_name: akpsi
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
