version: '3'

services:
  db:
    image: sqlite
    volumes:
      - data:/var/lib/sqlite/data
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: akpsi
    volumes:
      - .:/akpsi
    ports:
      - "8000:8000"

volumes:
  data:
    external: true