# Generated by Django 2.2.1 on 2019-06-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190615_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
