# Generated by Django 2.2.1 on 2019-06-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
