# Generated by Django 2.2.1 on 2019-06-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_brother'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brother',
        ),
    ]
