# Generated by Django 2.2.1 on 2019-06-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20190624_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgroup',
            old_name='team',
            new_name='members',
        ),
    ]
